In [35]:
# Import libraries
import pandas as pd
import requests
import re
from shapely.geometry import Point
import geopandas as gpd   # conda install -c conda-forge geopandas

In [36]:
# Acquistion of data

In [37]:
#Bicimad

In [38]:
df_bicimad_original = pd.read_csv('../data/bicimad_stations.csv')
df_bicimad = df_bicimad_original [['name', 'address', 'geometry_coordinates']]

def lat (x):
    b= x.split(',')
    c= b[0].replace('[','')
    d= float(c)
    return d
    
def long (x):
    b= x.split(',')
    c= b[1].replace(']','')
    d= float(c)
    return d

In [141]:
df_bicimad['Longitude.bicimad'] = df_bicimad.apply(lambda x: lat(x['geometry_coordinates']),axis=1)
df_bicimad['Latitude.bicimad'] = df_bicimad.apply(lambda x: long(x['geometry_coordinates']),axis=1)
df_bicimad

/Users/Izaskun/miniconda3/envs/bicimad/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/Users/Izaskun/miniconda3/envs/bicimad/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,name,address,geometry_coordinates,Latitude,Longitude,Latitude.bicimad,Longitude.bicimad
0,Puerta del Sol A,Puerta del Sol nº 1,"[-3.7018341, 40.4172137]",-3.701834,40.417214,40.417214,-3.701834
1,Puerta del Sol B,Puerta del Sol nº 1,"[-3.701602938060457, 40.41731271011562]",-3.701603,40.417313,40.417313,-3.701603
2,Miguel Moya,Calle Miguel Moya nº 1,"[-3.7058415, 40.4205886]",-3.705842,40.420589,40.420589,-3.705842
3,Plaza Conde Suchil,Plaza del Conde del Valle de Súchil nº 3,"[-3.7069171, 40.4302937]",-3.706917,40.430294,40.430294,-3.706917
4,Malasaña,Calle Manuela Malasaña nº 5,"[-3.7025875, 40.4285524]",-3.702587,40.428552,40.428552,-3.702587
...,...,...,...,...,...,...,...
259,Ciudad Universitaria 1,Avenida de la Complutense (Metro Ciudad Univer...,"[-3.72699, 40.44375]",-3.726990,40.443750,40.443750,-3.726990
260,Ciudad Universitaria 2,Avenida de la Complutense (Metro Ciudad Univer...,"[-3.72693, 40.44342]",-3.726930,40.443420,40.443420,-3.726930
261,Facultad Biología,Calle José Antonio Novais frente al nº 12,"[-3.7272945, 40.4483322]",-3.727295,40.448332,40.448332,-3.727295
262,Facultad Derecho,Avenida Complutense nº 23,"[-3.72937, 40.45109]",-3.729370,40.451090,40.451090,-3.729370
263,Zurbano,Calle Zurbano nº 90,"[-3.69281, 40.43837]",-3.692810,40.438370,40.438370,-3.692810

In [143]:
df_bicimad_final= df_bicimad[['name', 'address', 'Latitude.bicimad', 'Longitude.bicimad']]

In [144]:
df_bicimad_final

,name,address,Latitude.bicimad,Longitude.bicimad
0,Puerta del Sol A,Puerta del Sol nº 1,40.417214,-3.701834
1,Puerta del Sol B,Puerta del Sol nº 1,40.417313,-3.701603
2,Miguel Moya,Calle Miguel Moya nº 1,40.420589,-3.705842
3,Plaza Conde Suchil,Plaza del Conde del Valle de Súchil nº 3,40.430294,-3.706917
4,Malasaña,Calle Manuela Malasaña nº 5,40.428552,-3.702587
...,...,...,...,...
259,Ciudad Universitaria 1,Avenida de la Complutense (Metro Ciudad Univer...,40.443750,-3.726990
260,Ciudad Universitaria 2,Avenida de la Complutense (Metro Ciudad Univer...,40.443420,-3.726930
261,Facultad Biología,Calle José Antonio Novais frente al nº 12,40.448332,-3.727295
262,Facultad Derecho,Avenida Complutense nº 23,40.451090,-3.729370
263,Zurbano,Calle Zurbano nº 90,40.438370,-3.692810

In [157]:
%%time
df_bicimad_final['location_bicimad']= df_bicimad_final.apply(lambda x: to_mercator (x['Latitude.bicimad'], x['Longitude.bicimad']), axis=1)

/Users/Izaskun/miniconda3/envs/bicimad/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [159]:
df_bicimad_final.head()

,name,address,Latitude.bicimad,Longitude.bicimad,location_bicimad
0,Puerta del Sol A,Puerta del Sol nº 1,40.417214,-3.701834,POINT (4499223.648366921 -412373.2851572837)
1,Puerta del Sol B,Puerta del Sol nº 1,40.417313,-3.701603,POINT (4499234.670122574 -412347.498528782)
2,Miguel Moya,Calle Miguel Moya nº 1,40.420589,-3.705842,POINT (4499599.340516399 -412820.3206106317)
3,Plaza Conde Suchil,Plaza del Conde del Valle de Súchil nº 3,40.430294,-3.706917,POINT (4500679.707306497 -412940.3068148262)
4,Malasaña,Calle Manuela Malasaña nº 5,40.428552,-3.702587,POINT (4500485.866677178 -412457.3286497012)

In [152]:
#Centros Deportivos

In [80]:
url = 'https://datos.madrid.es/egob/catalogo/212808-0-espacio-deporte.json'
r= requests.get(url).json()
df = pd.json_normalize(r['@graph'])
df_centros_deportivos= df [['title', 'address.street-address', 'location.latitude', 'location.longitude'] ]
df_centros_deportivos

,title,address.street-address,location.latitude,location.longitude
0,Campo de Golf del Centro Nacional de Golf,CALLE ARROYO DEL MONTE 5,40.485508,-3.735279
1,Campo de Golf del Club de Golf Olivar de la Hi...,CALLE VIA DE DUBLIN 12,40.465351,-3.611293
2,Campos de Fútbol Ernesto Cotorruelo,CALLE VIA LUSITANA 5,40.381231,-3.724179
3,Centro Comercial Dreams - Palacio Municipal de...,CALLE SILVANO 77,40.462913,-3.635734
4,Centro de Alto Rendimiento del Consejo Superio...,CALLE MARTIN FIERRO 5,40.436812,-3.731957
...,...,...,...,...
606,Piscina SAGE Fitness,CALLE ESCALONA 59,40.397182,-3.761105
607,Pista de Patinaje Paco de Lucía,AUDITORIO PACO DE LUCIA,40.385278,-3.764155
608,Pista de petanca Centro de Mayores La Vaguada,AVENIDA MONFORTE DE LEMOS 36,40.479033,-3.708264
609,Polideportivo Antonio Magariños,CALLE SERRANO 129,40.442522,-3.686096
610,WiZink Center,"CALLE JORGE JUAN 99 Avenida de Felipe II, s/n",40.423284,-3.672104

In [160]:
df_centros_deportivos['location_centros']= df_centros_deportivos.apply(lambda x: to_mercator (x['location.latitude'], x['location.longitude']), axis=1)

/Users/Izaskun/miniconda3/envs/bicimad/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [162]:
df_centros_deportivos.head()

,title,address.street-address,location.latitude,location.longitude,location_centros
0,Campo de Golf del Centro Nacional de Golf,CALLE ARROYO DEL MONTE 5,40.485508,-3.735279,POINT (4506826.154319164 -416104.2065551275)
1,Campo de Golf del Club de Golf Olivar de la Hi...,CALLE VIA DE DUBLIN 12,40.465351,-3.611293,POINT (4504582.255355831 -402273.7208142197)
2,Campos de Fútbol Ernesto Cotorruelo,CALLE VIA LUSITANA 5,40.381231,-3.724179,POINT (4495218.036163405 -414865.966552915)
3,Centro Comercial Dreams - Palacio Municipal de...,CALLE SILVANO 77,40.462913,-3.635734,POINT (4504310.842371287 -404999.9123872458)
4,Centro de Alto Rendimiento del Consejo Superio...,CALLE MARTIN FIERRO 5,40.436812,-3.731957,POINT (4501405.320516344 -415733.6645299961)

In [81]:
#Input

In [82]:
#centro = input("Enter a centro: ")
#centro_ejemplo= "Campo de Golf del Centro Nacional de Golf"

In [83]:
# Distance function

In [148]:
def to_mercator(lat, long):
    # transform latitude/longitude data in degrees to pseudo-mercator coordinates in metres
    c = gpd.GeoSeries([Point(lat, long)], crs=4326)
    c = c.to_crs(3857)
    return c

In [163]:
def distance_meters(location_centros, location_bicimad):
    # return the distance in metres between to latitude/longitude pair point in degrees (i.e.: 40.392436 / -3.6994487)
    return location_centros.distance(location_bicimad)

In [85]:

#def row_filter (df, cat_var, cat_values, sort_by):
#    df = df[ df [cat_var] .isin(cat_values) ].sort_values(by=sort_by, ascending=False)
# mask = df1['player_country'].isin(['Spain'])

In [86]:
cat_values= ["Campo de Golf del Centro Nacional de Golf"]

In [94]:
#tt= df_centros_deportivos[df_centros_deportivos['location.latitude'].isin([cat_values])]
t= df_centros_deportivos[df_centros_deportivos['title'].isin(cat_values)][['location.latitude','location.longitude']]

In [103]:
t

   location.latitude  location.longitude
0          40.485508           -3.735279

In [115]:
t.values

array([[40.48550817, -3.73527898]])

In [116]:
lista= t.values.tolist()[0]

In [117]:
lista

[40.4855081729451, -3.735278975476509]

In [128]:
lista[1]

-3.735278975476509

In [135]:
def name_to_coordinates(name):
    t= df_centros_deportivos[df_centros_deportivos['title'].isin([name])][['location.latitude','location.longitude']]
    lista= t.values.tolist()[0]
    lat= lista[0]
    lon= lista[1]
    return lat, lon

In [136]:
name_to_coordinates ("Campo de Golf del Centro Nacional de Golf")

(40.4855081729451, -3.735278975476509)

In [ ]:
#Mergeo los dos dataframes

In [165]:
interest_points_bicimad = df_bicimad_final.assign(key=0).merge(df_centros_deportivos.assign(key=0), how='left', on = 'key')

In [167]:
interest_points_bicimad.head()

,name,address,Latitude.bicimad,Longitude.bicimad,location_bicimad,key,title,address.street-address,location.latitude,location.longitude,location_centros
0,Puerta del Sol A,Puerta del Sol nº 1,40.417214,-3.701834,POINT (4499223.648366921 -412373.2851572837),0,Campo de Golf del Centro Nacional de Golf,CALLE ARROYO DEL MONTE 5,40.485508,-3.735279,POINT (4506826.154319164 -416104.2065551275)
1,Puerta del Sol A,Puerta del Sol nº 1,40.417214,-3.701834,POINT (4499223.648366921 -412373.2851572837),0,Campo de Golf del Club de Golf Olivar de la Hi...,CALLE VIA DE DUBLIN 12,40.465351,-3.611293,POINT (4504582.255355831 -402273.7208142197)
2,Puerta del Sol A,Puerta del Sol nº 1,40.417214,-3.701834,POINT (4499223.648366921 -412373.2851572837),0,Campos de Fútbol Ernesto Cotorruelo,CALLE VIA LUSITANA 5,40.381231,-3.724179,POINT (4495218.036163405 -414865.966552915)
3,Puerta del Sol A,Puerta del Sol nº 1,40.417214,-3.701834,POINT (4499223.648366921 -412373.2851572837),0,Centro Comercial Dreams - Palacio Municipal de...,CALLE SILVANO 77,40.462913,-3.635734,POINT (4504310.842371287 -404999.9123872458)
4,Puerta del Sol A,Puerta del Sol nº 1,40.417214,-3.701834,POINT (4499223.648366921 -412373.2851572837),0,Centro de Alto Rendimiento del Consejo Superio...,CALLE MARTIN FIERRO 5,40.436812,-3.731957,POINT (4501405.320516344 -415733.6645299961)

In [ ]:
#df_bicimad['Longitude.bicimad'] = df_bicimad.apply(lambda x: lat(x['geometry_coordinates']),axis=1)
interest_points_bicimad['Distance']= interest_points_bicimad.apply(lambda x: distance_meters (x ['location_bicimad'], x ['location_centros']), axis=1 )